### ISSUE TITLE
absolute paths for .a files

### ISSUE THREAD

**Issue by kylemcdonald** [admsyn/OFPlugin#22]
it looks like OFPlugin adds absolute paths to the linker search paths? i just noticed this upon sending some project files back and forth between me and golan. noticed it specifically with the ofxLibdc and ofxLeapMotion addons.

**Comment by admsyn** [comment]
I think this is fixed, but it's a little tell for sure or if Xcode is doing some magic.

Due to some Xcode behaviour I don't seem to have any control over, adding an addon with a static lib will add an absolute path to your Library Search Path settings, but it doesn't actually seem to be necessary (as in, I can delete it, clean / rebuild etc and everything works fine). Internally, the lib is linked via relative path.

If this isn't fixed, feel free to re-open!
